main:
  - name: Services
    url: "#service"
    weight: 2
  - name: Our Story
    url: "about"
    identifier: our-story
    weight: 4
  - name: Programs
    url: "#product"
    identifier: programs
    weight: 5
  - name: Weight Management
    url: "product/weight-management"
    parent: programs
    weight: 1
  - name: PCOD/PCOS Reversal
    url: "product/pcod-pcos-reversal"
    parent: programs
    weight: 2
  - name: Diabetes Management
    url: "product/diabetes-management"
    parent: programs
    weight: 3
  - name: Stress Management
    url: "product/stress-management"
    parent: programs
    weight: 4
  - name: Gut Management
    url: "product/gut-management"
    parent: programs
    weight: 5
  - name: Thyroid Reversal
    url: "product/thyroid-reversal"
    parent: programs
    weight: 6
  - name: Hormone Balance
    url: "product/hormone-balance"
    parent: programs
    weight: 7
  - name: Infertility Therapy
    url: "product/infertility-therapy"
    parent: programs
    weight: 8
  - name: Holistic Wellness
    url: "product/holistic-wellness"
    parent: programs
    weight: 9
  - name: Testimonials
    url: "#testimonial"
    identifier: testimonials
    weight: 6
  - name: Success Stories
    url: "testimonials/success-stories"
    parent: testimonials
    weight: 1
  - name: Client Feedbacks
    url: "testimonials/client-feedbacks"
    parent: testimonials
    weight: 2
  - name: Our Story
    url: "about"
    identifier: our-story
    weight: 4
  - name: Meet Dt. Niharika
    url: "about/meet-dt-niharika"
    parent: our-story
    weight: 1
  - name: Media & Mentions
    url: "about/media-mentions"
    parent: our-story
    weight: 2
  - name: About Us
    url: "about/about-us"
    parent: our-story
    weight: 3
  - name: Blog
    url: "#blog"
    weight: 7
sitemap:
  - name: Home
    url: ""
    weight: 1
  - name: Contact Us
    url: "contact"
    weight: 2
  - name: Products
    url: "product"
    weight: 3
  - name: Blog
    url: "blog"
    weight: 4
