titleAddition: Nutrition & Wellness
images:
  - favicon.ico
ogLocale: en_US
titleHome: Dt. Niharika Singh - Nutritionist & Dietitian
twitterSite: '@dt.niharika_singh'
twitterCreator: '@dt.niharika_singh'
schemaType: Organization
schemaName: Fitness Vibe by Dt. Niharika
schemaAuthor: Dt. Niharika Singh
schemaAuthorTwitter: ''
schemaAuthorLinkedIn: ''
schemaAuthorGitHub: ''
schemaLocale: en-US
schemaLogo: logo-hyas.png
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: hyas.png
schemaImageWidth: 1280
schemaImageHeight: 640
schemaTwitter: ''
schemaLinkedIn: ''
schemaGitHub: ''
themeColor: '#3ac58d'
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: '320'
imageResponsive: true
imageConvertTo: webp
imageImageSizes:
  - '480'
  - '720'
  - '1080'
  - '1280'
  - '1600'
  - '2048'
singleSize: false
imageAddClass: img-fluid lazyload blur-up
defaultImage: default-image.png
fillImage: 1280x720 Center
footerContact:
  topTitle: Let's Start
  title: The Start of a Dream
  button: Get in Touch
titleSeparator: '-'
description: >-
  Personalized diet, nutrition, and Ayurvedic wellness plans by Dt. Niharika
  Singh for PCOS, thyroid, diabetes, infertility, weight management, and
  long-term health.
alert: false
alertDismissable: true
alertText: >-
  Deliver web projects 10x faster. <a class="alert-link"
  href="https://www.netlify.com/whitepaper/" target="_blank" rel="noopener">Get
  the free enterprise paper </a>
blogPageURL: blog
logo: images/site-navigation/logo.jpg
footerLogo: images/site-navigation/logo.jpg
contactLink: contact
copyright: All right reserved copyright © Fitness Vibe 2035
googleAnalytics: YOUR GOOGLE ANALYTICS CODE
fabformURL: 'https://fabform.io/f/JpTXRUa'
address:
  phone: +91 8305779442
  email: info@dietitianniharika.in
  address: >-
    Unit 103, World One High Street, Kharar - Landran Road, Sector 115, Mohali,
    Punjab 140307
  openingHours: Open from 10am to 6pm (close at 5pm Sundays)
map:
  APIkey: YOUR GOOGLE MAP API
  latitude: '23.7783741'
  longitude: '90.3746808'
  pinImage: images/pin.png
social: {}
